### ISSUE TITLE
Implement an ICDC data dictionary importer

### ISSUE THREAD

**Issue by jiaola** [cancerDHC/ccdh-terminology-service#66]
## Description
Need to import ICDC data into our database.

### Tasks
Check here when tasks are adequately answered

- [x] 1. Where is the data dictionary, if it exists, in whatever form it exists?
- [x] 2. What are the limitations to the current data dictionary, if it exists?
- [x] 3. What are the timelines for this data dictionary to be upgrade into something that would be more useful for us?
- [x] 4. Who is primary ICDC contact for this data dict?

#### 1. Where is the data dictionary, if it exists, in whatever form it exists?
So far, this [repo dir](https://github.com/CBIIT/icdc-model-tool/tree/master/model-desc) contains the model in 2 files (though there is a 3rd .mdf schema file):
- [Entities (called "categories") and their attributes (called "props")](https://github.com/CBIIT/icdc-model-tool/blob/master/model-desc/icdc-model.yml)
- [Attributes (called "props") and their enumerations (called "types")](https://github.com/CBIIT/icdc-model-tool/blob/master/model-desc/icdc-model-props.yml)

#### 2. What are the limitations to the current data dictionary, if it exists?
- Structure: From what I can see so far, structure is a bit different, but that may be about it.
- Completeness: It doesn't seem like a very big model. Is this it?

#### 3. What are the timelines for this data dictionary to be upgrade into something that would be more useful for us?
(Don't know yet)

#### 4. Who is primary ICDC contact for this data dict?
Mark Jensen, I believe.

**Comment by joeflack4** [comment]
Note: when ready to work on this, I have some notes in Workflowy I've saved from my discussion w/ Jim & Phil that will be very useful to go over again.
