### ISSUE TITLE
Update node query for: `​/models​/{model}​/entities​/{entity}​/attributes​/{attribute}`

### ISSUE THREAD

**Issue by joeflack4** [cancerDHC/ccdh-terminology-service#94]
## Description
There is an inconsistency in the kind of response you get based on the model you are querying, whether node model or CRDC-H.

When querying a CRDC-H entity attr here, you get mappings to nodes, as well as an enumeration.

When querying a node entity attr, you just get a small amount of information about the attribute.

## Tasks
- [ ] 1. Should this inconsistency exist? (I don't think so)
- [ ] 2. If not, should node entity attr queries also return the same amount of information as a CRDC-H query?
- [ ] 3. For CRDC-H, it appears to return an enumeration. But that is handled by another endpoint. Is this expected? What should it return instead if not?

## Examples
https://terminology.ccdh.io/models/CRDC-H/entities/BodySite/attributes/qualifier
```json
{
  "system": "CRDC-H",
  "entity": "BodySite",
  "attribute": "qualifier",
  "definition": "A qualifier that further refines or specifies the location of the body site (e.g. to indicate laterality, upper v. lower, containment, etc).",
  "node_attributes": [
    {
      "system": "PDC",
      "entity": "Sample",
      "attribute": "biospecimen_laterality",
      "definition": "For tumors in paired organs, designates the side on which the specimen was obtained."
    },
    {
      "system": "GDC",
      "entity": "Sample",
      "attribute": "biospecimen_laterality",
      "definition": "For tumors in paired organs, designates the side on which the specimen was obtained."
    }
  ],
  "concept_references": [
    {
      "code": "C25228",
      "uri": "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C25228",
      "designation": "Right",
      "definition": "Being or located on or directed toward the side of the body to the east when facing north.",
      "reference": "https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI%20Thesaurus&code=C25228"
    },
    {
      "code": "C25229",
      "uri": "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C25229",
      "designation": "Left",
      "definition": "Being or located on or directed toward the side of the body to the west when facing north.",
      "reference": "https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI%20Thesaurus&code=C25229"
    },
    {
      "code": "C13332",
      "uri": "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C13332",
      "designation": "Bilateral",
      "definition": "Affecting both sides of the body or a matched pair of organs.",
      "reference": "https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI%20Thesaurus&code=C13332"
    },
    {
      "code": "C43234",
      "uri": "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C43234",
      "designation": "Not Reported",
      "definition": "Not provided or available.",
      "reference": "https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI%20Thesaurus&code=C43234"
    },
    {
      "code": "C17998",
      "uri": "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C17998",
      "designation": "Unknown",
      "definition": "Not known, not observed, not recorded, or refused.",
      "reference": "https://ncit.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI%20Thesaurus&code=C17998"
    }
  ]
}
```

https://terminology.ccdh.io/models/PDC/entities/Sample/attributes/biospecimen_laterality
```json
{
  "system": "PDC",
  "entity": "Sample",
  "attribute": "biospecimen_laterality",
  "definition": "For tumors in paired organs, designates the side on which the specimen was obtained."
}
```
